name: db_cracker_tamaengs
description: Tool for accessing educational database systems.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.11
  intl: ^0.18.1
  cupertino_icons: ^1.0.5 # Update ke versi terbaru yang stabil

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  # Tambahkan font Courier jika belum ada
  fonts:
    - family: Courier
      fonts:
        - asset: assets/fonts/CourierPrime-Regular.ttf
        - asset: assets/fonts/CourierPrime-Bold.ttf
          weight: 700